language: objective-c
osx_image: xcode9
sudo: false

env:
  global:
    - SCHEME="TouchAreaInsets"
    - IOS_SDK="iphonesimulator11"
    - DESTINATION="OS=11.0,name=iPhone 8"

script:
  - xcodebuild clean test -project "TouchAreaInsets.xcodeproj" -scheme "$SCHEME" -sdk "$IOS_SDK" -destination "$DESTINATION" -configuration Release CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty -c
