language: objective-c
osx_image: xcode8
sudo: false

env:
  global:
    - SCHEME="TouchAreaInsets"
    - IOS_SDK="iphonesimulator10.2"
    - DESTINATION="OS=10.2,name=iPhone 7"

script:
  - xcodebuild clean test -project "TouchAreaInsets.xcodeproj" -scheme "$SCHEME" -sdk "$IOS_SDK" -destination "$DESTINATION" -configuration Release CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty -c
